backend:
  name: git-gateway
  repo: luigimassaroACN/hugo-starter-kit
  branch: main
  auth_type: implicit
  app_id: GITHUB_CLIENT_ID
  login: true
  
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
