backend:
  name: github
  repo: luigimassaroACN/hugo-starter-kit
  branch: main
  auth_type: pkce
  app_id: MZ3lq0ywhUSOmF27Cz1PqeYZuuMSKaY2
  base_url: https://dev-5luunm78xnqjk5gc.auth0.com
  login: true
  site_domain: hugo-starter-kit.netlify.app
  
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
